name: Push develop and Deploy
 
on:
  push:
    branches: ["build/add-dockerfile"]

env:
  NAMESPACE: DRMP
  PROJECT_NAME: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.NAMESPACE }}/${{ env.PROJECT_NAME }}:latest
          platforms: linux/amd64 

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Dokploy deployment
        env:
          DOKPLOY_WEBHOOK_URL: ${{ secrets.DOKPLOY_WEBHOOK_URL }}
        run: |
          curl -X POST "$DOKPLOY_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{"ref":"'"${{ github.ref }}"'"}'
